LESSONS = [
    {
        "title": "Greetings & Basics",
        "vocab": [
            ("hello", "שלום"),
            ("goodbye", "להתראות"),
            ("good morning", "בוקר טוב"),
            ("good night", "לילה טוב"),
            ("please", "בבקשה"),
            ("thank you", "תודה"),
            ("yes", "כן"),
            ("no", "לא"),
            ("sorry", "סליחה"),
            ("friend", "חבר"),
        ],
    },
    {
        "title": "Numbers & Time",
        "vocab": [
            ("one", "אחת"),
            ("two", "שתיים"),
            ("three", "שלוש"),
            ("four", "ארבע"),
            ("five", "חמש"),
            ("six", "שש"),
            ("seven", "שבע"),
            ("eight", "שמונה"),
            ("nine", "תשע"),
            ("ten", "עשר"),
        ],
    },
    {
        "title": "Family",
        "vocab": [
            ("mother", "אמא"),
            ("father", "אבא"),
            ("brother", "אח"),
            ("sister", "אחות"),
            ("grandmother", "סבתא"),
            ("grandfather", "סבא"),
            ("son", "בן"),
            ("daughter", "בת"),
            ("uncle", "דוד"),
            ("aunt", "דודה"),
        ],
    },
    {
        "title": "Food & Drink",
        "vocab": [
            ("bread", "לחם"),
            ("water", "מים"),
            ("milk", "חלב"),
            ("apple", "תפוח"),
            ("cheese", "גבינה"),
            ("meat", "בשר"),
            ("egg", "ביצה"),
            ("honey", "דבש"),
            ("salt", "מלח"),
            ("wine", "יין"),
        ],
    },
    {
        "title": "Common Verbs",
        "vocab": [
            ("eat", "לאכול"),
            ("drink", "לשתות"),
            ("sleep", "לישון"),
            ("walk", "ללכת"),
            ("run", "לרוץ"),
            ("speak", "לדבר"),
            ("read", "לקרוא"),
            ("write", "לכתוב"),
            ("listen", "להקשיב"),
            ("see", "לראות"),
        ],
    },
]