LESSONS = [
    {
        "title": "Greetings & Basics",
        "vocab": [
            ("hello", "שלום", "shalom"),
            ("goodbye", "להתראות", "lehitraot"),
            ("good morning", "בוקר טוב", "boker tov"),
            ("good night", "לילה טוב", "laila tov"),
            ("please", "בבקשה", "bevakasha"),
            ("thank you", "תודה", "todah"),
            ("yes", "כן", "ken"),
            ("no", "לא", "lo"),
            ("sorry", "סליחה", "slicha"),
            ("friend", "חבר", "chaver"),
        ],
    },
    {
        "title": "Numbers & Time",
        "vocab": [
            ("one", "אחת", "achat"),
            ("two", "שתיים", "shtayim"),
            ("three", "שלוש", "shalosh"),
            ("four", "ארבע", "arba"),
            ("five", "חמש", "chamesh"),
            ("six", "שש", "shesh"),
            ("seven", "שבע", "sheva"),
            ("eight", "שמונה", "shmoneh"),
            ("nine", "תשע", "tesha"),
            ("ten", "עשר", "eser"),
        ],
    },
    {
        "title": "Family",
        "vocab": [
            ("mother", "אמא", "ima"),
            ("father", "אבא", "aba"),
            ("brother", "אח", "ach"),
            ("sister", "אחות", "achot"),
            ("grandmother", "סבתא", "savta"),
            ("grandfather", "סבא", "saba"),
            ("son", "בן", "ben"),
            ("daughter", "בת", "bat"),
            ("uncle", "דוד", "dod"),
            ("aunt", "דודה", "doda"),
        ],
    },
    {
        "title": "Food & Drink",
        "vocab": [
            ("bread", "לחם", "lechem"),
            ("water", "מים", "mayim"),
            ("milk", "חלב", "chalav"),
            ("apple", "תפוח", "tapuach"),
            ("cheese", "גבינה", "gvina"),
            ("meat", "בשר", "basar"),
            ("egg", "ביצה", "beitza"),
            ("honey", "דבש", "dvash"),
            ("salt", "מלח", "melach"),
            ("wine", "יין", "yayin"),
        ],
    },
    {
        "title": "Common Verbs",
        "vocab": [
            ("eat", "לאכול", "lechol"),
            ("drink", "לשתות", "lishtot"),
            ("sleep", "לישון", "lishon"),
            ("walk", "ללכת", "lalechet"),
            ("run", "לרוץ", "larutz"),
            ("speak", "לדבר", "ledaber"),
            ("read", "לקרוא", "likro"),
            ("write", "לכתוב", "lichtov"),
            ("listen", "להקשיב", "lehakshiv"),
            ("see", "לראות", "lir'ot"),
        ],
    },
]