LESSONS = [
    {
        "title": "Greetings & Basics",
        "level": 1,
        "emoji": "👋",
        "vocab": [
            ("hello", "שלום", "shalom"),
            ("goodbye", "להתראות", "lehitraot"),
            ("good morning", "בוקר טוב", "boker tov"),
            ("good night", "לילה טוב", "laila tov"),
            ("please", "בבקשה", "bevakasha"),
            ("thank you", "תודה", "todah"),
            ("yes", "כן", "ken"),
            ("no", "לא", "lo"),
            ("sorry", "סליחה", "slicha"),
            ("friend", "חבר", "chaver"),
        ],
    },
    {
        "title": "Numbers & Time",
        "level": 1,
        "emoji": "🔢",
        "vocab": [
            ("one", "אחת", "achat"),
            ("two", "שתיים", "shtayim"),
            ("three", "שלוש", "shalosh"),
            ("four", "ארבע", "arba"),
            ("five", "חמש", "chamesh"),
            ("six", "שש", "shesh"),
            ("seven", "שבע", "sheva"),
            ("eight", "שמונה", "shmoneh"),
            ("nine", "תשע", "tesha"),
            ("ten", "עשר", "eser"),
        ],
    },
    {
        "title": "Family",
        "level": 1,
        "emoji": "👨👩👧",
        "vocab": [
            ("mother", "אמא", "ima"),
            ("father", "אבא", "aba"),
            ("brother", "אח", "ach"),
            ("sister", "אחות", "achot"),
            ("grandmother", "סבתא", "savta"),
            ("grandfather", "סבא", "saba"),
            ("son", "בן", "ben"),
            ("daughter", "בת", "bat"),
            ("uncle", "דוד", "dod"),
            ("aunt", "דודה", "doda"),
        ],
    },
    {
        "title": "Food & Drink",
        "level": 1,
        "emoji": "🍎",
        "vocab": [
            ("bread", "לחם", "lechem"),
            ("water", "מים", "mayim"),
            ("milk", "חלב", "chalav"),
            ("apple", "תפוח", "tapuach"),
            ("cheese", "גבינה", "gvina"),
            ("meat", "בשר", "basar"),
            ("egg", "ביצה", "beitza"),
            ("honey", "דבש", "dvash"),
            ("salt", "מלח", "melach"),
            ("wine", "יין", "yayin"),
        ],
    },
    {
        "title": "Common Verbs",
        "level": 1,
        "emoji": "⚡",
        "vocab": [
            ("eat", "לאכול", "lechol"),
            ("drink", "לשתות", "lishtot"),
            ("sleep", "לישון", "lishon"),
            ("walk", "ללכת", "lalechet"),
            ("run", "לרוץ", "larutz"),
            ("speak", "לדבר", "ledaber"),
            ("read", "לקרוא", "likro"),
            ("write", "לכתוב", "lichtov"),
            ("listen", "להקשיב", "lehakshiv"),
            ("see", "לראות", "lir'ot"),
        ],
    },
    {
        "title": "Colors",
        "level": 2,
        "emoji": "🎨",
        "vocab": [
            ("red", "אדום", "adom"),
            ("blue", "כחול", "kachol"),
            ("yellow", "צהוב", "tzahov"),
            ("green", "ירוק", "yarok"),
            ("black", "שחור", "shachor"),
            ("white", "לבן", "lavan"),
            ("orange", "כתום", "katom"),
            ("purple", "סגול", "sagol"),
            ("pink", "ורוד", "varod"),
            ("brown", "חום", "chum"),
        ],
    },
    {
        "title": "Body Parts",
        "level": 2,
        "emoji": "🦵",
        "vocab": [
            ("head", "ראש", "rosh"),
            ("eye", "עין", "ayin"),
            ("ear", "אוזן", "ozen"),
            ("nose", "אף", "af"),
            ("mouth", "פה", "peh"),
            ("hand", "יד", "yad"),
            ("leg", "רגל", "regel"),
            ("foot", "כף רגל", "kaf regel"),
            ("heart", "לב", "lev"),
            ("stomach", "בטן", "beten"),
        ],
    },
    {
        "title": "Days of the Week",
        "level": 2,
        "emoji": "📅",
        "vocab": [
            ("Sunday", "יום ראשון", "yom rishon"),
            ("Monday", "יום שני", "yom sheni"),
            ("Tuesday", "יום שלישי", "yom shlishi"),
            ("Wednesday", "יום רביעי", "yom revi'i"),
            ("Thursday", "יום חמישי", "yom chamishi"),
            ("Friday", "יום שישי", "yom shishi"),
            ("Saturday", "שבת", "shabbat"),
            ("week", "שבוע", "shavua"),
            ("day", "יום", "yom"),
            ("today", "היום", "hayom"),
        ],
    },
    {
        "title": "Weather",
        "level": 2,
        "emoji": "☀️",
        "vocab": [
            ("rain", "גשם", "geshem"),
            ("sun", "שמש", "shemesh"),
            ("wind", "רוח", "ruach"),
            ("snow", "שלג", "sheleg"),
            ("cloud", "ענן", "anan"),
            ("storm", "סופה", "sefah"),
            ("hot", "חם", "cham"),
            ("cold", "קר", "kar"),
            ("sky", "שמיים", "shamayim"),
            ("umbrella", "מטרייה", "mitria"),
        ],
    },
    {
        "title": "Animals",
        "level": 2,
        "emoji": "🐶",
        "vocab": [
            ("dog", "כלב", "kelev"),
            ("cat", "חתול", "chatul"),
            ("bird", "ציפור", "tzipor"),
            ("horse", "סוס", "sus"),
            ("fish", "דג", "dag"),
            ("cow", "פרה", "parah"),
            ("sheep", "כבשה", "kivsah"),
            ("chicken", "תרנגול", "tarnegal"),
            ("lion", "אריה", "aryeh"),
            ("elephant", "פיל", "pil"),
        ],
    },
    {
        "title": "Around the House",
        "level": 3,
        "emoji": "🏠",
        "vocab": [
            ("kitchen", "מטבח", "mitbach"),
            ("bedroom", "חדר שינה", "cheder sheina"),
            ("bathroom", "אמבטיה", "ambatia"),
            ("door", "דלת", "delet"),
            ("window", "חלון", "chalon"),
            ("table", "שולחן", "shulchan"),
            ("chair", "כיסא", "kiseh"),
            ("bed", "מיטה", "mitah"),
            ("wall", "קיר", "kir"),
            ("floor", "רצפה", "ritzpa"),
        ],
    },
    {
        "title": "Clothing",
        "level": 3,
        "emoji": "👕",
        "vocab": [
            ("shirt", "חולצה", "chultza"),
            ("pants", "מכנסיים", "michnasayim"),
            ("shoes", "נעליים", "naalayim"),
            ("coat", "מעיל", "me'il"),
            ("hat", "כובע", "kova"),
            ("dress", "שמלה", "simlah"),
            ("socks", "גרביים", "garbayim"),
            ("sweater", "סוודר", "sveder"),
            ("skirt", "חצאית", "chatza'it"),
            ("jacket", "ז'קט", "jeket"),
        ],
    },
    {
        "title": "Places in the City",
        "level": 3,
        "emoji": "🏙️",
        "vocab": [
            ("street", "רחוב", "rechov"),
            ("hospital", "בית חולים", "beit cholim"),
            ("bank", "בנק", "bank"),
            ("park", "פארק", "park"),
            ("museum", "מוזיאון", "muzeon"),
            ("library", "ספרייה", "sifria"),
            ("restaurant", "מסעדה", "misada"),
            ("store", "חנות", "chanut"),
            ("police station", "תחנת משטרה", "tachanat mishtara"),
            ("airport", "נמל תעופה", "nemal teufa"),
        ],
    },
    {
        "title": "Transport & Travel",
        "level": 3,
        "emoji": "✈️",
        "vocab": [
            ("car", "מכונית", "mechonit"),
            ("bus", "אוטובוס", "otobus"),
            ("train", "רכבת", "rakevet"),
            ("plane", "מטוס", "matos"),
            ("boat", "סירה", "sira"),
            ("bicycle", "אופניים", "ofanayim"),
            ("taxi", "מונית", "monit"),
            ("ticket", "כרטיס", "kartis"),
            ("driver", "נהג", "nahag"),
            ("journey", "נסיעה", "nesi'a"),
        ],
    },
    {
        "title": "Professions",
        "level": 3,
        "emoji": "👷",
        "vocab": [
            ("doctor", "רופא", "rofeh"),
            ("teacher", "מורה", "moreh"),
            ("engineer", "מהנדס", "mahandes"),
            ("police officer", "שוטר", "shoter"),
            ("chef", "שף", "shef"),
            ("lawyer", "עורך דין", "orech din"),
            ("artist", "אמן", "oman"),
            ("driver", "נהג", "nahag"),
            ("farmer", "איכר", "ikar"),
            ("pilot", "טייס", "tayas"),
        ],
    },
    {
        "title": "Emotions & Feelings",
        "level": 4,
        "emoji": "💭",
        "vocab": [
            ("happy", "שמח", "sameach"),
            ("sad", "עצוב", "atzuv"),
            ("angry", "כועס", "ko'es"),
            ("afraid", "מפחד", "mechafed"),
            ("surprised", "מופתע", "mufte'a"),
            ("worried", "מודאג", "mudag"),
            ("excited", "מתרגש", "mitragesh"),
            ("proud", "גאה", "ge'eh"),
            ("lonely", "בודד", "boded"),
            ("jealous", "מקנא", "mekaneh"),
        ],
    },
    {
        "title": "Health & Sickness",
        "level": 4,
        "emoji": "🩺",
        "vocab": [
            ("sick", "חולה", "choleh"),
            ("pain", "כאב", "ke'ev"),
            ("medicine", "תרופה", "trufah"),
            ("fever", "חום", "chom"),
            ("headache", "כאב ראש", "ke'ev rosh"),
            ("rest", "מנוחה", "menucha"),
            ("cough", "שיעול", "shi'ul"),
            ("clinic", "מרפאה", "mirpah"),
            ("throat", "גרון", "garon"),
            ("recovery", "החלמה", "hachlama"),
        ],
    },
    {
        "title": "Education & Study",
        "level": 4,
        "emoji": "🎓",
        "vocab": [
            ("exam", "מבחן", "mivchan"),
            ("homework", "שיעורי בית", "shi'urei bayit"),
            ("knowledge", "ידע", "yeda"),
            ("question", "שאלה", "she'elah"),
            ("answer", "תשובה", "tshuvah"),
            ("university", "אוניברסיטה", "universita"),
            ("student", "תלמיד", "talmid"),
            ("lesson", "שיעור", "shi'ur"),
            ("notebook", "מחברת", "machberet"),
            ("degree", "תואר", "to'ar"),
        ],
    },
    {
        "title": "Nature & Environment",
        "level": 4,
        "emoji": "🌿",
        "vocab": [
            ("tree", "עץ", "etz"),
            ("river", "נהר", "nahar"),
            ("mountain", "הר", "har"),
            ("forest", "יער", "ya'ar"),
            ("desert", "מדבר", "midbar"),
            ("earth", "אדמה", "adamah"),
            ("lake", "אגם", "agam"),
            ("flower", "פרח", "pereach"),
            ("leaf", "עלה", "aleh"),
            ("island", "אי", "ee"),
        ],
    },
    {
        "title": "Daily Routine",
        "level": 4,
        "emoji": "⏰",
        "vocab": [
            ("wake up", "לקום", "lakum"),
            ("shower", "מקלחת", "miklechet"),
            ("breakfast", "ארוחת בוקר", "aruchat boker"),
            ("lunch", "ארוחת צהריים", "aruchat tzahorayim"),
            ("dinner", "ארוחת ערב", "aruchat erev"),
            ("work", "עבודה", "avodah"),
            ("alarm clock", "שעון מעורר", "sha'on me'orer"),
            ("brush teeth", "לצחצח שיניים", "letzachtzach shinayim"),
            ("get dressed", "להתלבש", "lehitlabesh"),
            ("relax", "להירגע", "leheraga"),
        ],
    },
    {
        "title": "Abstract Concepts",
        "level": 5,
        "emoji": "🧠",
        "vocab": [
            ("freedom", "חופש", "chofesh"),
            ("justice", "צדק", "tzedek"),
            ("truth", "אמת", "emet"),
            ("wisdom", "חוכמה", "chochmah"),
            ("courage", "אומץ", "ometz"),
            ("hope", "תקווה", "tikvah"),
            ("peace", "שלום", "shalom"),
            ("love", "אהבה", "ahavah"),
            ("power", "כוח", "koach"),
            ("responsibility", "אחריות", "achrayut"),
        ],
    },
    {
        "title": "Advanced Verbs",
        "level": 5,
        "emoji": "🔥",
        "vocab": [
            ("succeed", "להצליח", "lehatzliach"),
            ("fail", "להיכשל", "lehikashael"),
            ("achieve", "להשיג", "lehasig"),
            ("improve", "לשפר", "leshaper"),
            ("understand", "להבין", "lehavin"),
            ("decide", "להחליט", "lehakhlit"),
            ("believe", "להאמין", "leha'amin"),
            ("create", "ליצור", "litzor"),
            ("influence", "להשפיע", "lehashpia"),
            ("prove", "להוכיח", "lehokhi'ach"),
        ],
    },
    {
        "title": "Idioms & Sayings",
        "level": 5,
        "emoji": "💬",
        "vocab": [
            ("break a leg", "בהצלחה", "behatzlacha"),
            ("a piece of cake", "קלי קלות", "kali kalot"),
            ("needle in a haystack", "מחט בערמת שחת", "machat be'aremat shachat"),
            ("hit the nail on the head", "פגע בול", "paga boul"),
            ("the ball is in your court", "הכדור אצלך", "hakadur etzlecha"),
            ("burn the midnight oil", "להישאר ער עד מאוחר", "lehisha'er er ad me'uchar"),
            ("once in a blue moon", "לעיתים רחוקות", "le'itim rechokot"),
            ("under the weather", "לא במיטבו", "lo bemitavo"),
            ("blessing in disguise", "ברכה במסווה", "bracha bemasveh"),
            ("better late than never", "עדיף מאוחר מאשר אף פעם", "adif me'uchar mi'af paam"),
        ],
    },
    {
        "title": "Money & Business",
        "level": 5,
        "emoji": "💰",
        "vocab": [
            ("money", "כסף", "kesef"),
            ("profit", "רווח", "revach"),
            ("loss", "הפסד", "hefsed"),
            ("investment", "השקעה", "hashka'ah"),
            ("salary", "משכורת", "miskoret"),
            ("business", "עסק", "esek"),
            ("customer", "לקוח", "lakoach"),
            ("contract", "חוזה", "chozah"),
            ("loan", "הלוואה", "halva'ah"),
            ("tax", "מס", "mas"),
        ],
    },
    {
        "title": "Society & Justice",
        "level": 5,
        "emoji": "⚖️",
        "vocab": [
            ("law", "חוק", "chok"),
            ("rights", "זכויות", "zchuyot"),
            ("court", "בית משפט", "beit mishpat"),
            ("government", "ממשלה", "memshala"),
            ("citizen", "אזרח", "ezrach"),
            ("crime", "פשע", "pesha"),
            ("punishment", "עונש", "onesh"),
            ("democracy", "דמוקרטיה", "demokratia"),
            ("election", "בחירות", "bechirot"),
            ("society", "חברה", "chevrah"),
        ],
    },
]